baseURL = 'https://samq64.github.io/'
locale = 'en-CA'
title = 'Samuel Q'
copyright = '© 2026 Samuel Q.'

pluralizelisttitles = false
disableKinds = ["RSS"]

[taxonomies]
  tag = "tags"

[security]
  allowContent = ['.*']

[markup]
  [markup.highlight]
    style = "tokyonight-night"
    codeFences = true
    lineNos = true
