baseURL = 'https://samuelq.dev/'
locale = 'en-CA'
title = 'Samuel Q'
copyright = '© 2026 Samuel Q.'

pluralizelisttitles = false
disableKinds = ["RSS"]
enableRobotsTXT = true

[params]
  description = 'Personal site of Samuel Q.'

[taxonomies]
  tag = "tags"
  category = "categories"

[security]
  allowContent = ['^text/(html|markdown)$']

[markup]
  [markup.highlight]
    style = "tokyonight-night"
    codeFences = true
    lineNos = true

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 10

[[menu.main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 20
