{{- /* Rendered per page by the pwa partial. A .js partial, so Hugo leaves the JSON quotes alone. */ -}}
{{- $page := . -}}
{{- $prefix := printf "%s-" (path.Base $page.RelPermalink) -}}
{{- /*
  The app is the page, what it names, and what it renders; a script's imports are bundled into it.
  Every face is precached, not just the three preloaded, or an app taken offline early loses them.
  The fonts are listed apart because they outlive edits to the rest, which one name would refetch.
*/ -}}
{{- $built := partialCached "built-assets" $page $page.Path -}}
{{- $app := slice $page.RelPermalink (partialCached "main-css" $page).RelPermalink -}}
{{- range $built.styles | append $built.scripts -}}
  {{- $app = $app | append .RelPermalink -}}
{{- end -}}
{{- with $page.Resources.Get "character.svg" -}}
  {{- $app = $app | append .RelPermalink -}}
{{- end -}}
{{- $fonts := partialCached "font-urls" $page -}}
{{- $version := printf "%s%s" $prefix (substr (crypto.SHA256 (delimit $app "|")) 0 12) -}}
{{- $fontVersion := printf "%sfonts-%s" $prefix (substr (crypto.SHA256 (delimit $fonts "|")) 0 12) -}}
/*
  Generated by layouts/_partials/sw.js — edit that, not this.

  Everything precached is hashed or unchanging, so each cache is named from its own list: change
  any of them and that name changes, and activate drops what the names no longer in use held.
*/
const APP = "{{ $version }}";
const PREFIX = "{{ $prefix }}";
const START = "{{ $page.RelPermalink }}";
const PRECACHE = {
  [APP]: {{ $app | jsonify }},
  "{{ $fontVersion }}": {{ $fonts | jsonify }},
};

self.addEventListener("install", (event) => {
  event.waitUntil(
    Promise.all(
      Object.entries(PRECACHE).map(([name, urls]) =>
        caches.open(name).then((cache) => cache.addAll(urls)),
      ),
    ).then(() => self.skipWaiting()),
  );
});

/* Only this app's own caches are dropped, in case another page ever registers a worker. */
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith(PREFIX) && !(name in PRECACHE))
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

/* The app cache: anything reaching here was not precached, so it belongs to this build. */
function save(request, response) {
  if (!response.ok) return response;
  const copy = response.clone();
  caches.open(APP).then((cache) => cache.put(request, copy));
  return response;
}

/*
  Documents come from the network first, falling back to the cache and then the board itself,
  so a deploy is picked up as soon as the device is online. Everything else is hashed, so the
  cache answers outright.

  Cross-origin requests are passed over: a controlled page's extension requests reach the
  worker too, and the cache takes http alone, so storing one would throw.
*/
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => save(request, response))
        .catch(() => caches.match(request).then((cached) => cached || caches.match(START))),
    );
    return;
  }

  event.respondWith(
    caches
      .match(request)
      .then((cached) => cached || fetch(request).then((response) => save(request, response))),
  );
});
