{{- /*
  The bliss board's service worker, rendered per page by the pwa partial. Kept as a .js
  partial so Hugo treats it as text and leaves the quotes in the JSON alone.
*/ -}}
{{- $page := . -}}
{{- $prefix := printf "%s-" (path.Base $page.Path) -}}
{{- /*
  The page, the stylesheets and scripts it names, and the images it renders. A script's imports
  are bundled into it, so they need no entry of their own.

  The fonts are read back out of the built stylesheet, since esbuild is what named them and
  they are reachable no other way. Without them an app installed and taken offline before it
  had drawn any text would fall back to the system's.
*/ -}}
{{- $css := partial "main-css" $page -}}
{{- $urls := slice $page.RelPermalink $css.RelPermalink -}}
{{- range findRE `/[^)"']+\.woff2` $css.Content | uniq -}}
  {{- $urls = $urls | append . -}}
{{- end -}}
{{- $built := partial "built-assets" $page -}}
{{- range $built.styles -}}
  {{- $urls = $urls | append .RelPermalink -}}
{{- end -}}
{{- range $built.scripts -}}
  {{- $urls = $urls | append .RelPermalink -}}
{{- end -}}
{{- with $page.Resources.Get "character.svg" -}}
  {{- $urls = $urls | append .RelPermalink -}}
{{- end -}}
{{- $cache := printf "%s%s" $prefix (substr (crypto.SHA256 (delimit $urls "|")) 0 12) -}}
/*
  Generated by layouts/_partials/sw.js — edit that, not this.

  Everything precached below is either hashed or unchanging, so the cache name is derived
  from the list itself: a deploy that changes any of them changes the name, and activate
  drops what the previous name held.
*/
const CACHE = "{{ $cache }}";
const PREFIX = "{{ $prefix }}";
const START = "{{ $page.RelPermalink }}";
const PRECACHE = {{ $urls | jsonify }};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

/* Only this app's own caches are dropped, in case another page ever registers a worker. */
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith(PREFIX) && name !== CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

function save(request, response) {
  if (!response.ok) return response;
  const copy = response.clone();
  caches.open(CACHE).then((cache) => cache.put(request, copy));
  return response;
}

/*
  Documents come from the network first, so a deploy is picked up the moment the device is
  online, and fall back to the cache and then to the board itself when it isn't. Anything
  else is hashed or unchanging, so the cache can answer it outright.

  Only what the site serves itself is touched. Every request a controlled page makes reaches
  the worker, whatever its scope, and an extension's are among them: the cache takes http
  requests alone, so storing one of those throws instead of being ignored. Passing on them
  without responding leaves the browser to fetch them exactly as it would have.
*/
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  if (new URL(request.url).origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => save(request, response))
        .catch(() => caches.match(request).then((cached) => cached || caches.match(START))),
    );
    return;
  }

  event.respondWith(
    caches
      .match(request)
      .then((cached) => cached || fetch(request).then((response) => save(request, response))),
  );
});
